config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :rooms do
    resources :bookings, only: [:new, :create]
  end
  
  resources :bookings, only: [:index, :show, :destroy]
  resources :meeting_participants, only: [:update]
  
  namespace :admin do
    get "users/index"
    get "users/edit"
    get "users/update"
    get 'dashboard', to: 'admin#dashboard'
    resources :users, only: [:index, :edit, :update]
  end
  resources :bookings do
    collection do
      get :my_invitations
    end
    member do
      post :invite
      post :respond_to_invitation
    end
  end
  
  root to: 'rooms#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Meeting Room Booking</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_include_tag 'application', media: 'all' %>

</head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <%= link_to "Meeting Room Booking", root_path, class: "navbar-brand" %>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav me-auto">
            <li class="nav-item"><%= link_to "Rooms", rooms_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "My Bookings", bookings_path, class: "nav-link" %></li>
            <% if current_user&.admin? %>
              <li class="nav-item"><%= link_to "Admin Dashboard", admin_dashboard_path, class: "nav-link" %></li>
            <% end %>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <span class="nav-link">
                  <%= current_user.name %> (<%= current_user.position %>)
                </span>
              </li>
              <li class="nav-item">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Register", new_user_registration_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4">
      <% if notice %><div class="alert alert-success"><%= notice %></div><% end %>
      <% if alert %><div class="alert alert-danger"><%= alert %></div><% end %>
      <%= yield %>
    </div>
  </body>
</html>